name: "argocd-lint-and-diff"
description: "This action will produce a diff between the to be merged code and the running state"
inputs:
  argocd_server:
    description: "the url of the argocd server to use"
    required: true
  argocd_token:
    description: "The token to authenticate with argocd"
    required: true
  argocd_lovely_plugin_token:
    description: "Token to use that authenticates the argocd loverly plugin? todo: ask @mihai"
    required: true
  github_token:
    description: "Token to use to authenticate to github for commenting on the pr"

runs:
  using: "composite"
  steps:
    - uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "4.4.0"

    - uses: imranismail/setup-kustomize@v1

    - uses: GETProtocolLab/argocd-diff-action@master
      name: ArgoCD Diff testing
      with:
        argocd-server-url: ${{ inputs.argocd_server }}
        argocd-token: ${{ inputs.argocd_token }}
        argocd-version: v2.1.6
        argocd-extra-cli-args: --grpc-web
        argocd-lovely-plugin-token: ${{ inputs.argocd_lovely_plugin_token }}
        github-token: ${{ secrets.github_token }}
