name: "Docker Build and Push Dev Images"
description: "Builds the Docker image and pushes it to the specified registry"
inputs:
  registry:
    description: "Registry's host"
    required: false
    default: "ghcr.io"
  user:
    description: "Registry's user"
    required: false
    default: ${{ github.actor }}
  password:
    description: "Registry user's password or token"
    required: true
  image:
    description: "Docker image name without tag"
    required: true
  tag:
    description: "Docker image tag"
    required: true
  build_args:
    description: "Environment variables passed to docker build"
    required: false
  extra_tags:
    description: "Additional tags, needs the full version of tags with image name"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Gitlab Registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.user }}
        password: ${{ inputs.password }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3.6.1
      with:
        images: ${{ inputs.image }}

    - name: Build and push prod image
      uses: docker/build-push-action@v2.7.0
      with:
        context: ${{ github.workspace }}
        platforms: linux/amd64
        push: true
        build-args: ${{ inputs.build_args }}
        tags: |
          ${{ inputs.image }}:${{ inputs.tag }}
          ${{ inputs.extra_tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
