name: "argocd"
description: "This action will update a overlay with a image tag and tell argocd to sync"
inputs:
  overlay:
    description: "the kustomize directory to deploy"
    required: true
  image:
    description: "the image that should be updated"
    required: true
  image_tag:
    description: "the tag to set for the image"
    required: true
  argocd_server:
    description: "the url of the argocd server to use"
    required: true
  argocd_token:
    description: "The token to authenticate with argocd"
    required: true
  argocd_app:
    description: "The app to sync"
    required: true

runs:
  using: "composite"
  steps:
    - uses: imranismail/setup-kustomize@v1

    - name: Update overlay with new image tag
      run: |
        cd $TARGET
        kustomize edit set image $IMAGE=:$TAG
        cat kustomization.yml
      shell: bash
      env:
        TARGET: ${{ inputs.overlay }}
        IMAGE: ${{ inputs.image }}
        TAG: ${{ inputs.image_tag }}

    - uses: actionsx/prettier@v2
      with:
        args: --write ${{ inputs.overlay }}/kustomization.yml

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Deploy ${{ github.ref_name }} (${{ github.sha }}) to ${{ inputs.overlay }}

    - run: docker run argoproj/argocd:v2.4.11 argocd app sync $ARGOCD_APP --grpc-web --server $SERVER --auth-token $AUTH_TOKEN
      shell: bash
      env:
        ARGOCD_APP: ${{ inputs.argocd_app }}
        SERVER: ${{ inputs.argocd_server }}
        AUTH_TOKEN: ${{ inputs.argocd_token }}
