name: lint and diff

on:
  workflow_call:

jobs:
  prettier_deploy_config:
    runs-on: [self-hosted, ubuntu20.04-self]
    steps:
      - uses: actions/checkout@v3
      - uses: actionsx/prettier@v2
        with:
          args: --check ./deploy

  argocd_diff:
    runs-on: [self-hosted, ubuntu20.04-self]
    if: github.base_ref  == 'development' || github.base_ref  == 'master' || github.base_ref  == 'production'
    steps:
      - id: argocd
        shell: bash
        run: |
          if [ "$GIT_REF" == "development" ]; then
            echo "server-url=argocd.euc1.t.get-protocol.dev" >> $GITHUB_OUTPUT
            echo "token=$EUC1TESTING_TOKEN" >> $GITHUB_OUTPUT
          elif [ "$GIT_REF" == "master" ]; then
            echo "server-url=argocd.euc1.s.get-protocol.dev" >> $GITHUB_OUTPUT
            echo "token=$EUC1STAGING_TOKEN" >> $GITHUB_OUTPUT
          elif [ "$GIT_REF" == "production" ]; then
            echo "server-url=argocd.euc1.get-protocol.cloud" >> $GITHUB_OUTPUT
            echo "token=$EUC1_TOKEN" >> $GITHUB_OUTPUT
          fi
        env:
          GIT_REF: ${{ github.base_ref }}
          EUC1TESTING_TOKEN: ${{ secrets.ARGOCD_EUC1TESTING_API_AUTH }}
          EUC1STAGING_TOKEN: ${{ secrets.ARGOCD_EUC1STAGING_API_AUTH }}
          EUC1_TOKEN: ${{ secrets.ARGOCD_EUC1_API_AUTH }}

      - uses: actions/checkout@v3
      - uses: imranismail/setup-kustomize@v1

      - uses: GETProtocolLab/argocd-diff-action@master
        name: ArgoCD Diff testing
        with:
          argocd-server-url: ${{ steps.argocd.outputs.server-url }}
          argocd-token: ${{ steps.argocd.outputs.token }}
          argocd-version: v2.1.6
          argocd-extra-cli-args: --grpc-web
          argocd-lovely-plugin-token: ${{ secrets.GH_PACKAGES_ACCESS }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
