name: lint

permissions:
  id-token: write
  contents: read

on:
  pull_request:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      prettier:
        type: boolean
        default: true
      dockle:
        type: boolean
        default: true

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  prettier:
    runs-on: [self-hosted, ubuntu20.04-self]
    if: ${{ inputs.prettier }}
    steps:
      - uses: actions/checkout@v3
      - uses: actionsx/prettier@v2
        with:
          args: --check .
  dockle:
    runs-on: [self-hosted, ubuntu20.04-self]
    if: ${{ inputs.dockle }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Dockle Security Check
        uses: erzz/dockle-action@v1
        with:
          image: ${{ inputs.image }}
          failure-threshold: fatal
          exit-code: 1 # Stops pipeline if fatal issues found
