name: lint and diff

on:
  workflow_call:

jobs:
  prettier_deploy_config:
    runs-on: [self-hosted, ubuntu20.04-self]
    steps:
      - uses: actions/checkout@v3
      - uses: actionsx/prettier@v2
        with:
          args: --check ./deploy    

  argocd_diff:
    runs-on: [self-hosted, ubuntu20.04-self]
    if: github.base_ref  == 'development' || github.base_ref  == 'master' || github.base_ref  == 'production'
    steps:
      - id: argocd
        shell: bash
        run: |
          if [ "$GIT_REF" == "development" ]; then
            echo ::set-output name=server-url::argocd.euc1.t.get-protocol.dev
            echo ::set-output name=token::$EUC1TESTING_TOKEN
          elif [ "$GIT_REF" == "master" ]; then
            echo ::set-output name=server-url::argocd.euc1.s.get-protocol.dev
            echo ::set-output name=token::$EUC1STAGING_TOKEN
          elif [ "$GIT_REF" == "production" ]; then
            echo ::set-output name=server-url::argocd.euc1.get-protocol.cloud
            echo ::set-output name=token::$EUC1_TOKEN
          fi
        env:
          GIT_REF: ${{ github.base_ref }}
          EUC1TESTING_TOKEN: ${{ secrets.ARGOCD_EUC1TESTING_API_AUTH }}
          EUC1STAGING_TOKEN: ${{ secrets.ARGOCD_EUC1STAGING_API_AUTH }}
          EUC1_TOKEN: ${{ secrets.ARGOCD_EUC1_API_AUTH }}

      - uses: ../../argocd-diff
        with:
          argocd_server: ${{ steps.argocd.outputs.server-url }}
          argocd_token: ${{ steps.argocd.outputs.token }}
          argocd_lovely_plugin_token: ${{ secrets.GH_PACKAGES_ACCESS }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
